### ISSUE TITLE
Nightly builds?

### ISSUE THREAD

**Issue by Bluscream** [ReSpeak/TS3Hook#1]
Could you release nightly builds and tell travis not to build on README changes? ^^

**Comment by Flakebi** [comment]
> Commits that have [ci skip] or [skip ci] anywhere in the commit messages are ignored by Travis CI.

https://docs.travis-ci.com/user/customizing-the-build/

**Comment by Bluscream** [comment]
Ahh awesome, thanks.

**Comment by Bluscream** [comment]
@Splamy i don't have VS right now, could you compile and release `ac82959` please?

**Comment by Splamy** [comment]
@Bluscream done + a few improvements :P

**Comment by Bluscream** [comment]
Fucking awesome, i love you <3
