### ISSUE TITLE
r10 instead of eax

### ISSUE THREAD

**Issue by VisualStudio-zz** [ReSpeak/TS3Hook#13]
This isn't really an issue but more of an inquiry on how the patch works, I saw how it works mostly in IDA but when I go to breakpoint the packet out address I find the plaintext command in r10 instead of eax, why is this? Do you have any symbols for the teamspeak client? If so do you mind sharing?

EDIT: I'm terrible with asm if you haven't noticed.

This is an image of r10 being read out to IDA
![](https://ishr.ink/FZqQSQJe)

**Comment by Splamy** [comment]
Unfortunately I don't have any symbol files.
The reason why I'm not using `r10` is because, rdi is the address of the string (or similiar) struct, which holds the char pointer and the length, and for a safe print call I need the length, which i cant get from the char pointer alone

**Comment by VisualStudio-zz** [comment]
It's a c-style string so it's null-terminated, why didn't you just read til the null?

**Comment by Splamy** [comment]
Can you be sure that it is always 0-terminated? Sometimes ts sends some compressed/encrypted through the out-method when a packet got lost. In that case it won't be.
Also I've looked into the code again, another reason is compatibility. `r10` is never set in the out-method, so it's probably 'by chance' that this works in this particular version. `r10` is a volatile (temporary) register which means it's probably a temporary computation result from a called method. `rdi` instead is set over a fixed path which I can verify from a static analysis.

**Comment by Bluscream** [comment]
@VisualStudio-zz

**Comment by VisualStudio-zz** [comment]
Yes?

**Comment by Bluscream** [comment]
You were asked something

**Comment by VisualStudio-zz** [comment]
I wasn't asked anything.

**Comment by Bluscream** [comment]
> Can you be sure that it is always 0-terminated?

**Comment by Splamy** [comment]
Thats more a rhetorical question...

**Comment by Bluscream** [comment]
Well seems like this can be closed then.
