### ISSUE TITLE
Hide your connection info (ping, etc)

### ISSUE THREAD

**Issue by Bluscream** [ReSpeak/TS3Hook#14]
To hide your ping, packetloss, IP, etc... from other users just follow these simple steps:

1. [Get TS3Hook](https://github.com/ReSpeak/TS3Hook/blob/master/README.md#how-to-use).
2. Open the `HookConf.ini` file with wordpad or any other textfile editor.
3. Replace `blockcmds=` with `blockcmds=connectioninfoautoupdate,setconnectioninfo`.
4. Restart your client.
5. Enjoy some privacy ;)

**Comment by DatDraggy** [comment]
BOIIII that's pretty sick. 
Shouldn't this go into the wiki though?
Will this only block it for other users or is it gonna fuck with server queries too?

**Comment by Bluscream** [comment]
To block your client from sending how long you are typing a text message just follow steps 1-4 from above but also add `clientchatcomposing` to `blockcmds=`
