### ISSUE TITLE
auto ~cmd command on TS3 start up ?

### ISSUE THREAD

**Issue by Bosaa** [ReSpeak/TS3Hook#20]
Hi,
Thanks for this tool ! love it !
There is a way to add to HookConf.ini the options to send command when the teamspeak3 start up ?
Thanks :)

**Comment by Bluscream** [comment]
That makes no sense because you're not connected to any server at startup.

**Comment by Bosaa** [comment]
I meant that after you connect to server if you use "Connect on Startup" ...

**Comment by Bluscream** [comment]
You can use any LUA/python/C++ plugin to send commands on connect. What command do you need?

**Comment by Bosaa** [comment]
for example : `~cmdclientupdate~sclient_badges=overwolf=0:badges=1cb07348-34a4-4741-b50f-c41e584370f7`

**Comment by Bluscream** [comment]
Use https://r4p3.net/resources/custom-badges-aio.171/
