### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by HarmlessRetard** [ReSpeak/TS3Hook#23]
My friend is using the ts3 hook plugin and he was able to get his badges to flash many different variations and also completely cover his name with numerous amounts like so https://gyazo.com/1b4d4649adf8c5f4a20819a98a49441c
The problem is I cant figure out how to do so myself mainly because I hit max capacity in chat when I try to have several more badges like this: https://gyazo.com/e8f876f643264a380b7ca37d957019ef
and it only comes out looking like this: https://gyazo.com/f88686f205e0a92e7901a3235409c95d
So I was wondering if you could tell me how I would go about doing the rotation of badges along with how to have that many as shown in the first screenshot

**Comment by Bluscream** [comment]
Use https://r4p3.net/resources/custom-badges-aio.171/
