### ISSUE TITLE
Bypass TeaSpeak's notifymute

### ISSUE THREAD

**Issue by Bluscream** [ReSpeak/TS3Hook#28]
TeaSpeak recently added a new counterintuitive "[feature](https://github.com/TeaSpeak/TeaSpeak/commit/8d058c60150581fa22408a146e8f22615f7fe19d#diff-c9c91c29b41257aea3a3403cc606ad99R82)" that sends a notify to client's you blocked. You can bypass this by following this tutorial:

1. [Get TS3Hook](https://github.com/ReSpeak/TS3Hook/blob/master/README.md#how-to-use)
2. Start your TS client as admin to have the config file created at the location of your `ts3client_winXX.exe`
2. Open the `HookConf.ini` file with wordpad or any other textfile editor.
3. Add `clientmute` after `blockcmds=`
4. Restart your client.
5. Enjoy some privacy ;)

This is causing additional traffic for the server because he still sends you audio from clients that you muted and your client just drops it. Though the notify is very unnessecary in the first place so who cares 🤷‍♂️

**Comment by GitSimonHub** [comment]
idk for what this is

**Comment by Bluscream** [comment]
https://github.com/TeaSpeak/TeaSpeak/blob/master/config.yml#L112
