### ISSUE TITLE
Bypass virtualserver_hostmessage_mode clientside

### ISSUE THREAD

**Issue by Bluscream** [ReSpeak/TS3Hook#30]
Teamspeak servers don't drop clients when virtualserver_hostmessage_mode is 3 (MODALQUIT) but the client itself disconnect. So it should be possible to bypass by just checking if `virtualserver_hostmessage_mode=3` in `initserver` and replacing that by `virtualserver_hostmessage_mode=2`.

Could you do that @Najsr that would awesome :)

**Comment by Najsr** [comment]
I think you can close this issue. @Bluscream @Splamy
