### ISSUE TITLE
HookConf.ini not generated

### ISSUE THREAD

**Issue by lusu007** [ReSpeak/TS3Hook#43]
Hey,

I have version 3.1.10 in use and installed your TS3Hook. But the plugin does not generate a HookConf.ini in my binary root folder.

I followed your instructions. 

Greetings,
Lukas

**Comment by Bluscream** [comment]
Starte teamspeak als ADMIN

**Comment by lusu007** [comment]
Oh shit :D
Im sorry for that stupid "issue".
