### ISSUE TITLE
weird out commands and error sounds

### ISSUE THREAD

**Issue by alex720** [ReSpeak/TS3Hook#7]
randomly i hear a windows error sound a weird command get printed in the console.
![screenshot_5](https://user-images.githubusercontent.com/25466796/33036300-3eb0088c-ce2e-11e7-9049-bb2d228bf62d.jpg)

**Comment by exp111** [comment]
I had the same problem before I got a timeout (problem with my connection)

**Comment by Splamy** [comment]
some packets get through the hook already encrypted if they timed out (Mostly on disconnect or bad network connection). Whenever there happens to be a '\a' char in the text the console will sound a bell.

**Comment by Najsr** [comment]
Solved in https://github.com/ReSpeak/TS3Hook/commit/1373f52ca858e73880db95eaf2b298b39628bf22 @Splamy @Bluscream Can be closed.
